# Generated by Django 4.1.3 on 2022-11-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Abuelos',
        ),
        migrations.DeleteModel(
            name='Bisabuelos',
        ),
        migrations.DeleteModel(
            name='Bisnietos',
        ),
        migrations.DeleteModel(
            name='Hermanos',
        ),
        migrations.DeleteModel(
            name='Hijos',
        ),
        migrations.DeleteModel(
            name='Nietos',
        ),
        migrations.DeleteModel(
            name='Padres',
        ),
        migrations.DeleteModel(
            name='Primos_hermanos',
        ),
        migrations.DeleteModel(
            name='Sobrinos',
        ),
        migrations.DeleteModel(
            name='Tios',
        ),
        migrations.DeleteModel(
            name='Tios_abuelos',
        ),
    ]
